# This is a basic workflow to help you get started with actions
name: CI

# Controls when the wrokflow will run

on: 
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the actions tab
  workflow_dispatch: 
# A workflow run is made up of one or more jobs
jobs:  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps are a sequence of tasks executed as part of a job
    steps:
      # Checks out or downloads repository under $GITHUB_WORKSPACE   
      -  uses: actions/checkout@v4
      # Runs a single command using the runners shell
      -  name: Run a one-line script
         run: echo Hello, World!
      # Runs a seto of commands using the runners shell
      -  name: Run a multi-line script
         run: |
           echo Add other actions to build,
           echo test, and deploy your project.



















    
