name: workflow_run
on:
  pull_request_target:
 # workflow_run:
  #  workflows: ["CI"]
   # types: [completed]
    #branches:
     # -  'main'
permissions:
  contents: read
jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message on the console
        run: export HELLO="Hello wrold"
